### ISSUE TITLE
kernel coefficients

### ISSUE THREAD

**Issue by MaximilianLombardo** [SeojinBang/MKKC#1]
Hey Seojin,

Thanks for the pacakge, but I am wondering: why do you not constrain your kernel coefficients to sum to 1?

Thanks

**Comment by SeojinBang** [comment]
Hi, 

I'd rather use the L2 constraint on the kernel coefficients. As shown in the simulation experiments, the L2-based method outperformed the other competing methods using L1. 

Notably, these results agree well with the previous observations that the non-sparse solutions due to an L2 constraint on the kernel coefficients increase classification performance in applications to domains where the sources of data are carefully selected, and each source carries complementary information. 

I refer to Cortes et al. (UAI 2009, pg 109-116), Kloft et al. (NIPS 2009, pg 997-1005; JMLR 2011, pg953-997), and Yu et al. (BMC Bioinformatics 2010, 11: pg 309) for references.

If you want to see the relative weight for each view, simply <a href="https://www.codecogs.com/eqnedit.php?latex=\theta^{(v)}&space;/\sum_w&space;\theta^{(w)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\theta^{(v)}&space;/\sum_w&space;\theta^{(w)}" title="\theta^{(v)} /\sum_w \theta^{(w)}" /></a> will give you the relative weight for each view though.
